CC=g++
override CFLAGS+= -Wall
override CFLAGSL+=

SOURCES=                          \
    main.cpp                      \
    sorting.cpp

EXECUTABLE=exe

all:

	$(CC) $(CFLAGS) $(SOURCES) -o $(EXECUTABLE) $(CFLAGSL)